import {test} from 'node:test';
import assert from 'node:assert/strict';
import {execute} from '../src/runtime.js';
function run(code,lang='pseint',inputs=[],limits){const g=execute(code,lang,limits);let result=g.next(),output='',reads=[];while(!result.done){if(result.value.type==='output'){output+=result.value.text;result=g.next();}else{reads.push(result.value.name);assert.ok(inputs.length,'Missing input');result=g.next(inputs.shift());}}return {output,reads};}
const wrap=s=>'Algoritmo Prueba\n'+s+'\nFinAlgoritmo';
test('console executes output and arithmetic in all four source languages',()=>{for(const [lang,code] of Object.entries({pseint:wrap('Escribir 2 + 3 * 4'),python:'print(2 + 3 * 4)',javascript:'console.log(2 + 3 * 4);',c:'#include <stdio.h>\nint main(void) { printf("%d\\n", 2 + 3 * 4); return 0; }'}))assert.equal(run(code,lang).output,'14\n');});
test('console suspends for each input and validates types',()=>{const r=run(wrap('Definir edad Como Entero\nDefinir nombre Como Cadena\nLeer edad, nombre\nEscribir nombre, ": ", edad'),'pseint',['bad','18','Ana']);assert.deepEqual(r.reads,['edad','edad','nombre']);assert.match(r.output,/Entrada inválida/);assert.match(r.output,/Ana: 18\n$/);});
test('Python input and JavaScript prompt resume with supplied data',()=>{assert.equal(run('n = int(input())\nprint(n * 2)','python',['9']).output,'18\n');assert.equal(run('let n = Number(prompt()); console.log(n * 2);','javascript',['4']).output,'8\n');});
test('console handles conditions, descending loops, while and repeat',()=>{assert.equal(run(wrap('Definir i Como Entero\nPara i <- 3 Hasta 1 Con Paso -1 Hacer\nEscribir i\nFinPara\nMientras i < 2 Hacer\ni <- i + 1\nFinMientras\nRepetir\ni <- i - 1\nHasta Que i = 0\nSi i = 0 Entonces\nEscribir "Listo"\nSiNo\nEscribir "Mal"\nFinSi')).output,'3\n2\n1\nListo\n');});
test('console short-circuits logical conditions and prints booleans',()=>{assert.equal(run(wrap('Escribir Falso Y (1 / 0 > 2)')).output,'Falso\n');});
test('console rejects zero division, unsafe arithmetic and unsupported code',()=>{assert.throws(()=>run(wrap('Escribir 1 / 0')),/Línea 2.*cero/);assert.throws(()=>run(wrap('Escribir 999999999999999 * 100')),/rango seguro/);assert.throws(()=>run('fetch("https://example.com")','javascript'),/Línea/);});
test('empty loops and excessive output are bounded',()=>{assert.throws(()=>run(wrap('Mientras Verdadero Hacer\nFinMientras'),'pseint',[],{steps:40}),/límite de pasos/);assert.throws(()=>run(wrap('Repetir\nHasta Que Falso'),'pseint',[],{steps:40}),/límite de pasos/);assert.throws(()=>run(wrap('Escribir "123456"'),'pseint',[],{output:5}),/límite de salida/);});
test('runtime diagnostics map back to original Python lines',()=>{assert.throws(()=>run('a = 1\nb = 0\nprint(a / b)','python'),/Línea 3.*cero/);});
