import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';

test('Guest capabilities: room codes, isolated drafts, submissions, host permissions and removal',async()=>{
 const pg=new PGlite();
 await pg.exec(`create role anon; create role authenticated; create schema auth;
 create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
 create table auth.identities(user_id uuid,provider text,identity_data jsonb);
 create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 grant usage on schema auth to authenticated;`);
 await pg.exec(readFileSync(new URL('../supabase/schema.sql',import.meta.url),'utf8'));
 await pg.exec(readFileSync(new URL('../supabase/multilanguage.sql',import.meta.url),'utf8'));
 await pg.exec(readFileSync(new URL('../supabase/guest-rooms.sql',import.meta.url),'utf8'));
 const ids={},tokens={teacher:'a'.repeat(64),student:'b'.repeat(64),second:'c'.repeat(64),outsider:'d'.repeat(64),otherTeacher:'e'.repeat(64)};
 async function as(who,sql,params=[]){await pg.exec('begin; set local role anon;');await pg.query("select set_config('request.headers',$1,true)",[JSON.stringify({'x-guest-token':tokens[who]||''})]);try{const r=await pg.query(sql,params);await pg.exec('commit');return r.rows}catch(e){await pg.exec('rollback');throw e}}
 for(const who of Object.keys(tokens)){const [r]=await as(who,'select public.start_guest($1) as p',[who]);ids[who]=r.p.id;}
 await assert.rejects(as('missing',"select public.start_guest('No token')"));
 assert.equal((await as('missing','select * from public.rooms')).length,0);
 await assert.rejects(as('teacher','select * from private.guests'));
 const [{r:room}]=await as('teacher',"select public.create_room('Clase de prueba','DescripciÃ³n') as r");
 assert.match(room.join_code,/^[A-F0-9]{10}$/);
 const [{r:otherRoom}]=await as('student',"select public.create_room('Cualquiera puede crear','') as r");
 assert.notEqual(room.join_code,otherRoom.join_code);
 assert.equal((await as('outsider','select * from public.rooms')).length,0);
 assert.equal((await as('otherTeacher','select * from public.rooms')).length,0);
 await assert.rejects(as('outsider','insert into public.memberships(room_id,user_id) values($1,$2)',[room.id,ids.outsider]));
 assert.ok((await as('outsider',"select public.join_room('0000000000','Otra persona') as r"))[0].r.error);
 for(const who of ['student','second'])assert.equal((await as(who,'select public.join_room($1,$2) as r',[room.join_code,who]))[0].r.id,room.id);
 assert.equal((await as('student','select public.join_room($1,$2) as r',[room.join_code,'different name']))[0].r.id,room.id);
 assert.ok((await as('outsider','select public.join_room($1,$2) as r',[room.join_code,' STUDENT ']))[0].r.error);
 assert.equal((await as('student','select * from public.memberships')).length,1);
 assert.equal((await as('teacher','select * from public.memberships')).length,2);
 assert.equal((await as('student','select * from public.profiles')).length,1);
 await assert.rejects(as('student','update public.rooms set owner_id=$1',[ids.student]));
 assert.equal((await as('student',"update public.rooms set name='Hijacked' where id=$1 returning *",[room.id])).length,0);
 const [assignment]=await as('teacher',"insert into public.assignments(room_id,title) values($1,'Reto') returning *",[room.id]);
 assert.equal((await as('student','select * from public.assignments')).length,0);
 await assert.rejects(as('student','insert into public.submissions(assignment_id,student_id,source) values($1,$2,$3)',[assignment.id,ids.student,'secret']));
 await as('teacher','update public.assignments set published=true where id=$1',[assignment.id]);
 await as('student','insert into public.submissions(assignment_id,student_id,source) values($1,$2,$3)',[assignment.id,ids.student,'private draft']);
 assert.equal((await as('teacher','select * from public.submissions')).length,0);
 assert.equal((await as('second','select * from public.submissions')).length,0);
 await assert.rejects(as('second','insert into public.submissions(assignment_id,student_id,source) values($1,$2,$3)',[assignment.id,ids.student,'forged']));
 await as('student',"update public.submissions set source='final',status='submitted' where assignment_id=$1",[assignment.id]);
 assert.equal((await as('teacher','select * from public.submissions')).length,1);
 assert.ok((await as('student','select * from public.submissions'))[0].submitted_at);
 assert.equal((await as('student',"update public.submissions set source='cheat' where assignment_id=$1 returning *",[assignment.id])).length,0);
 await assert.rejects(as('student','update public.submissions set student_id=$1',[ids.second]));
 await assert.rejects(as('student','insert into public.reviews(assignment_id,student_id,score) values($1,$2,100)',[assignment.id,ids.student]));
 await as('teacher',"insert into public.reviews(assignment_id,student_id,score,feedback) values($1,$2,85,'Buen trabajo')",[assignment.id,ids.student]);
 assert.equal((await as('student','select * from public.reviews'))[0].score,'85.00');
 assert.equal((await as('second','select * from public.reviews')).length,0);
 assert.equal((await as('otherTeacher','select * from public.reviews')).length,0);
 await as('teacher',"update public.assignments set due_at=now()-interval '1 hour' where id=$1",[assignment.id]);
 await assert.rejects(as('second','insert into public.submissions(assignment_id,student_id,source) values($1,$2,$3)',[assignment.id,ids.second,'late']));
 await as('teacher','delete from public.memberships where user_id=$1',[ids.student]);
 assert.equal((await as('student','select * from public.rooms where id=$1',[room.id])).length,0);
 assert.equal((await as('student','select * from public.submissions')).length,0);
 assert.equal((await as('student','select * from public.reviews')).length,0);
 await assert.rejects(as('student','insert into public.memberships(room_id,user_id) values($1,$2)',[room.id,ids.student]));
 await assert.rejects(as('teacher','update public.rooms set owner_id=$1',[ids.otherTeacher]));
 assert.ok((await as('student','select public.join_room($1,$2) as r',[room.join_code,'newname']))[0].r.error);
 await as('teacher','update public.rooms set archived=true where id=$1',[room.id]);
 assert.ok((await as('outsider','select public.join_room($1,$2) as r',[room.join_code,'other']))[0].r.error);
 for(let i=0;i<11;i++)await as('outsider',"select public.join_room('0000000000','test')");
 assert.match((await as('outsider',"select public.join_room('0000000000','test') as r"))[0].r.error,/Espera un minuto/);
 assert.equal((await as('missing','select * from public.profiles')).length,0);
 // Reusing a visible profile UUID as a credential grants nothing.
 tokens.forged=ids.teacher;
 assert.equal((await as('forged','select * from public.rooms')).length,0);
 await pg.close();
});
