import {useCallback,useEffect,useState} from 'react';
import {LayoutGrid,Terminal,Plus,ChevronRight,RefreshCw,Users,Sun,Moon} from 'lucide-react';
import {Editor} from './LazyEditor';
import {RoomView} from './Room';
import {Brand,Empty,Loading,Modal,Notice,Submit,useAction} from './ui';
import {checked,db,message,starter,currentGuest,ensureGuest,joinRoom} from './lib';
import type {Language,Profile,Room} from './types';

export default function App(){
 const [theme,setTheme]=useState(()=>document.documentElement.dataset.theme==='dark'?'dark':'light');
 function toggleTheme(){const next=theme==='dark'?'light':'dark';setTheme(next);document.documentElement.dataset.theme=next;try{localStorage.setItem('entre-lineas-theme',next)}catch{/* Theme remains available when storage is disabled. */}}

 const [profile,setProfile]=useState<Profile|null>(null),[rooms,setRooms]=useState<Room[]>([]),[selected,setSelected]=useState<string|null>(null),[page,setPage]=useState<'editor'|'rooms'>('editor'),[dialog,setDialog]=useState<'create'|'join'|null>(()=>new URLSearchParams(location.search).has('sala')?'join':null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const [source,setSource]=useState(starter),[language,setLanguage]=useState<Language>('python'),[sourceLanguage,setSourceLanguage]=useState<Language>('pseint');
 const load=useCallback(async()=>{setError('');try{const p=await currentGuest();setProfile(p);if(p){setLoading(true);setRooms(await checked(db.from('rooms').select('*').order('created_at',{ascending:false}))??[])}}catch(e){setError(message(e))}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const room=rooms.find(r=>r.id===selected);
 async function entered(id:string){setDialog(null);history.replaceState(null,'',location.pathname);await load();setPage('rooms');setSelected(id)}
 return <div className="app-shell"><aside className="sidebar"><Brand/><div className="sidebar-section">NAVEGACIÓN</div><nav><button className={page==='editor'?'nav-active':''} onClick={()=>{setPage('editor');setSelected(null)}}><Terminal size={19}/> Traductor</button><button className={page==='rooms'&&!selected?'nav-active':''} onClick={()=>{setPage('rooms');setSelected(null)}}><LayoutGrid size={19}/> Mis salas <span>{rooms.length}</span></button></nav><div className="sidebar-section">SALAS</div><nav><button onClick={()=>setDialog('create')}><Plus size={19}/> Crear una sala</button><button onClick={()=>setDialog('join')}><Users size={19}/> Unirme a una sala</button></nav><div className="room-nav">{rooms.filter(r=>!r.archived).map(r=><button key={r.id} className={selected===r.id?'nav-active':''} onClick={()=>{setPage('rooms');setSelected(r.id)}}><span className="mini-room">{r.name.slice(0,1)}</span><span>{r.name}</span></button>)}</div><div className="account"><span className="avatar">{profile?.display_name.slice(0,2).toUpperCase()||'EL'}</span><div><b>{profile?.display_name||'Invitado'}</b><small>Este navegador</small></div></div></aside>
 <div className="main-shell"><header className="topbar"><div><Terminal size={18}/><span>Entre líneas</span><ChevronRight size={15}/><strong>{page==='editor'?'Traductor':room?.name||'Mis salas'}</strong></div><div className="topbar-actions"><span className="private-label">Sin registro</span><button className="secondary theme-toggle" onClick={toggleTheme} aria-label={theme==='dark'?'Activar modo claro':'Activar modo oscuro'} title={theme==='dark'?'Activar modo claro':'Activar modo oscuro'}>{theme==='dark'?<Sun size={17}/>:<Moon size={17}/>}<span>{theme==='dark'?'Modo claro':'Modo oscuro'}</span></button></div></header><main className="content">{error&&<Notice error>{error} <button className="text-button" onClick={()=>void load()}>Volver a intentar</button></Notice>}
 {page==='editor'?<><div className="page-heading"><div><h1>Traductor</h1><p>Escribe tu código y elige los lenguajes.</p></div></div><Editor source={source} onSource={setSource} language={language} onLanguage={setLanguage} sourceLanguage={sourceLanguage} onSourceLanguage={setSourceLanguage}/><p className="small">Tu práctica no se guarda automáticamente. Descarga el código antes de salir.</p></>:loading?<Loading/>:room&&profile?<RoomView key={room.id} room={room} userId={profile.id} onBack={()=>setSelected(null)} onReload={load}/>:<><div className="page-heading"><div><h1>Mis salas</h1></div><button className="primary" onClick={()=>setDialog('create')}><Plus size={17}/> Crear una sala</button></div><details className="inline-help"><summary>Cómo conservar mi acceso</summary><p>Tus salas y trabajos están vinculados a este navegador. Si borras sus datos o cambias de dispositivo, perderás el acceso.</p></details><div className="list-heading"><h2>{rooms.length} salas</h2><button className="icon" onClick={()=>void load()} aria-label="Actualizar salas"><RefreshCw size={17}/></button></div><div className="rooms-grid">{rooms.map((r,index)=><button className="room-card" key={r.id} onClick={()=>setSelected(r.id)}><div className={'room-card-cover cover-'+index%3}><span className="room-glyph">{'{ }'}</span><span className="pill light-pill">{r.archived?'Archivada':'Por invitación'}</span></div><div className="room-card-body"><span className="eyebrow">{r.owner_id===profile?.id?'ANFITRIÓN':'PARTICIPANTE'}</span><h3>{r.name}</h3>{r.description&&<p>{r.description}</p>}<div><span><Users size={16}/> Abrir sala</span><ChevronRight size={18}/></div></div></button>)}</div>{!rooms.length&&<Empty title="Aún no tienes salas">Crea una sala o entra con un código.<p><button className="secondary" onClick={()=>setDialog('join')}>Unirme con un código</button></p></Empty>}</>}
 </main><footer className="app-footer"><span>Autor: Cristoffer Betancour</span></footer></div>{dialog&&<RoomEntry mode={dialog} profile={profile} onClose={()=>{setDialog(null);history.replaceState(null,'',location.pathname)}} onEntered={entered}/>}</div>
}
function RoomEntry({mode,profile,onClose,onEntered}:{mode:'create'|'join';profile:Profile|null;onClose:()=>void;onEntered:(id:string)=>Promise<void>}){const a=useAction();const creating=mode==='create';return <Modal title={creating?'Crea una sala':'Únete a una sala'} onClose={onClose}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void a.run(async()=>{const name=String(f.get('display_name')).trim();await ensureGuest(name);const room=creating?await checked(db.rpc('create_room',{room_name:String(f.get('name')).trim(),room_description:String(f.get('description')).trim()})):await joinRoom(String(f.get('code')).trim(),name);await onEntered(room.id)})}}><label>Tu nombre<input name="display_name" required maxLength={80} defaultValue={profile?.display_name} placeholder="Ej. Ana López" autoComplete="off"/></label>{creating?<><label>Nombre de la sala<input name="name" required maxLength={100} placeholder="Ej. Fundamentos de programación · Grupo A"/></label><label>Descripción<textarea name="description" maxLength={2000} rows={3} placeholder="Qué aprenderá tu grupo…"/></label></>:<label>Código de la sala<input className="room-code-input" name="code" required maxLength={10} minLength={10} pattern="[a-fA-F0-9]{10}" defaultValue={new URLSearchParams(location.search).get('sala')||''} placeholder="Ej. A1B2C3D4E5" autoComplete="off" spellCheck={false}/></label>}<p className="small">Conserva este navegador: borrar sus datos o cambiar de dispositivo hace que pierdas el acceso.</p>{a.error&&<Notice error>{a.error}</Notice>}<div className="form-actions"><button type="button" className="secondary" onClick={onClose}>Cancelar</button><Submit busy={a.busy}>{creating?'Crear sala':'Entrar a la sala'}</Submit></div></form></Modal>}
