// Locate tokens only in code, never in comments or string contents. When the
// parser cannot identify one token, underline the instruction, not a guessed column.
function codeTokens(text,language){const tokens=[];let i=0;while(i<text.length){const c=text[i];if((c==='/'&&text[i+1]==='/')||(language==='python'&&c==='#'))break;if(c==='"'||c==="'"){const start=i++,q=c;let closed=false;while(i<text.length){if(text[i]==='\\'){i+=2;continue;}if(text[i++]===q){closed=true;break;}}tokens.push({value:text.slice(start,i),start,end:Math.min(i,text.length),string:true,closed});continue;}if(/\s/.test(c)){i++;continue;}const value=/^[A-Za-z_][A-Za-z_0-9]*|^(?:<=|>=|!=|==|<-|:=|\+\+|--|\d+(?:\.\d+)?)/.exec(text.slice(i))?.[0]||c;tokens.push({value,start:i,end:i+value.length});i+=value.length;}return tokens;}
export function diagnostic(source,language,error){const rows=source.split('\n'),line=Math.max(1,Math.min(error.line||1,rows.length)),excerpt=rows[line-1]||'',tokens=codeTokens(excerpt,language),code=tokens.filter(t=>!t.string);let message=error.message||'No se pudo interpretar esta instrucción.',hint='Revisa la instrucción resaltada y compárala con un ejemplo de la guía.',target=null,insertion=false;
 const named=/«([^»]+)»/.exec(message)?.[1];
 if(named){const hits=code.filter(t=>t.value.toLowerCase()===named.toLowerCase());if(hits.length===1)target=hits[0];if(/Declara/.test(message))hint=language==='pseint'?`Añade «Definir ${named} Como Entero» antes de usarla, o elige el tipo que corresponda.`:`Declara o asigna un valor a «${named}» antes de usarla y comprueba cómo escribiste su nombre.`;}
 const unclosed=tokens.find(t=>t.string&&!t.closed);
 if(unclosed){target=unclosed;message='La cadena de texto no tiene comilla de cierre.';hint=`Cierra el texto con ${unclosed.value[0]} antes de terminar la línea.`;}
 else if(/Símbolo no compatible/.test(message)){const value=message.split(': ').at(-1);target=code.find(t=>t.value===value)||null;hint=`El símbolo «${value}» no es válido aquí. Comprueba los operadores admitidos en la guía.`;}
 else if(/Instrucción.*compatible|Expresión no válida|expresión aún no.*incluida|llamadas a funciones/i.test(message)){
  const first=code[0]?.value||'';const array=code.find(t=>t.value==='[');const call=code.find((t,i)=>code[i+1]?.value==='('&&!['if','while','for','print','log','printf','scanf','range','input','Number','prompt'].includes(t.value));
  if(array){target=array;message='Los arreglos o listas todavía no están admitidos por este traductor.';hint='Usa variables individuales para este ejercicio; esta limitación no significa que el código sea inválido en su lenguaje.';}
  else if(['def','function','SubProceso','Subproceso'].includes(first)){target=code[0];message='Las funciones o subprocesos definidos por el usuario todavía no están admitidos.';hint='Escribe las instrucciones directamente en el programa principal.';}
  else if(language==='python'&&['if','while','for','else','elif'].includes(first)&&!excerpt.trimEnd().endsWith(':')){target={start:excerpt.trimEnd().length,end:excerpt.trimEnd().length};insertion=true;message=`Falta «:» al final de la cabecera de ${first}.`;hint='Añade dos puntos e indenta las instrucciones del bloque.';}
  else if(language==='pseint'&&first.toLowerCase()==='si'&&!code.some(t=>t.value.toLowerCase()==='entonces')){target={start:excerpt.trimEnd().length,end:excerpt.trimEnd().length};insertion=true;message='Falta «Entonces» después de la condición de Si.';hint='Ejemplo: Si edad >= 18 Entonces';}
  else if(language==='pseint'&&['mientras','para'].includes(first.toLowerCase())&&!code.some(t=>t.value.toLowerCase()==='hacer')){target={start:excerpt.trimEnd().length,end:excerpt.trimEnd().length};insertion=true;message='Falta «Hacer» al final de la cabecera del bucle.';hint='Completa la cabecera y cierra el bloque con FinMientras o FinPara.';}
  else if(call){target=call;message=`La llamada a «${call.value}» no está admitida en esta instrucción.`;hint='Usa las operaciones básicas de la guía. No todas las funciones del lenguaje se pueden traducir o ejecutar aquí.';}
  else if(language==='pseint'&&/^(Escribir|Leer)$/i.test(first)&&code.length===1){target={start:excerpt.trimEnd().length,end:excerpt.trimEnd().length};insertion=true;message=`Falta ${first.toLowerCase()==='leer'?'una variable':'un valor o texto'} después de ${first}.`;hint=first.toLowerCase()==='leer'?'Ejemplo: Leer edad':'Ejemplo: Escribir "Hola"';}
  else {message=`No se reconoce esta instrucción: ${excerpt.trim()||'(línea vacía)'}`;hint=language==='pseint'?'Comprueba la palabra inicial y la estructura: Escribir "Hola", Leer edad o edad <- 18.':'Comprueba la sintaxis de la instrucción. Si es válida en el lenguaje, puede quedar fuera del subconjunto admitido por la guía.';}
 }
 else if(/Falta una expresión/.test(message)){target={start:excerpt.trimEnd().length,end:excerpt.trimEnd().length};insertion=true;hint='Completa la operación con un número, una variable o una expresión.';}
 else if(/paréntesis/.test(message)){const stack=[];for(const t of code){if(t.value==='(')stack.push(t);if(t.value===')'){if(stack.length)stack.pop();else{target=t;break;}}}target=target||stack.at(-1)||null;hint='Cada paréntesis de apertura «(» necesita uno de cierre «)».';}
 else if(/Indentación|indentar|indentado/.test(message)){target={start:0,end:Math.max(1,excerpt.length-excerpt.trimStart().length)};hint='Usa espacios y alinea las instrucciones del mismo bloque. Después de una cabecera, indenta el bloque, por ejemplo con cuatro espacios.';}
 else if(/Falta Fin|Falta Hasta Que|Cierra tu programa/.test(message)){hint='Añade el cierre del bloque correspondiente antes de FinAlgoritmo. Revisa también dónde comienza ese bloque.';}
 else if(/tipo|tipos/.test(message)){hint='Comprueba los tipos de las variables y de los valores de esta instrucción; los números, textos y condiciones no son intercambiables.';}
 if(/dividir entre cero/.test(message))hint='Revisa el divisor de esta instrucción y valida que sea distinto de cero antes de dividir.';
 if(/límite de pasos/.test(message))hint='Comprueba que la condición del bucle pueda dejar de cumplirse y que actualizas sus variables.';
 if(/rango seguro|fuera de rango/.test(message))hint='Reduce los valores de esta operación; la consola no representa números de tamaño ilimitado.';
 const start=target?.start??(tokens[0]?.start||0),end=Math.max(start,target?.end??tokens.at(-1)?.end??excerpt.length);
 const from=rows.slice(0,line-1).reduce((n,s)=>n+s.length+1,0)+start;
 return {...error,line,message,hint,excerpt,column:start+1,endColumn:end+1,from,to:from+end-start,insertion,scope:target?'token':'instruction'};
}
export function formatDiagnostic(d){return `Línea ${d.line}, columna ${d.column}: ${d.message}\n${d.excerpt}\n${' '.repeat(d.column-1)}${'^'.repeat(Math.max(1,d.endColumn-d.column))}\n${d.hint}`;}
