import {translate} from './translator.js';

// Every supported input is normalized to the same typed PSeInt subset.
// Unknown constructs fail closed; they are never replaced with invented code.
export function convert(source,from='pseint',to='python'){
 if(!source.trim())return {code:'',errors:[],name:'mi_algoritmo',empty:true};
 try{
  const normalized=from==='pseint'?{code:source,map:source.split('\n').map((_,i)=>i+1)}:normalize(source,from);
  const result=translate(normalized.code,to==='pseint'?'python':to);
  if(result.errors.length)return {...result,errors:result.errors.map(e=>({...e,line:normalized.map[e.line-1]||1}))};
  return {...result,sourceMap:normalized.map,code:to==='pseint'?normalized.code:result.code};
 }catch(e){return {code:'',errors:[{line:e.line||1,message:e.message||'Revisa la sintaxis del programa.'}],name:'mi_algoritmo'}}
}
const fail=(line,message)=>{throw {line,message}};
function split(s,separator=','){let out=[],start=0,depth=0,q='';for(let i=0;i<s.length;i++){const c=s[i];if(q){if(c==='\\')i++;else if(c===q)q='';continue}if(c==='"'||c==="'")q=c;else if(c==='('||c==='[')depth++;else if(c===')'||c===']')depth--;else if(c===separator&&depth===0){out.push(s.slice(start,i).trim());start=i+1}}out.push(s.slice(start).trim());return out}
function protect(s,line){const strings=[];let out='';for(let i=0;i<s.length;i++){let c=s[i];if(c==='"'||c==="'"){const quote=c;let val='',closed=false;for(i++;i<s.length;i++){c=s[i];if(c===quote){closed=true;break}if(c==='\\'){const next=s[++i];if(!['n','r','t','\\','"',"'"].includes(next))fail(line,'Esta secuencia de escape todavía no es compatible.');val+=({n:'\n',r:'\r',t:'\t'}[next]??next)}else val+=c}if(!closed)fail(line,'Falta cerrar una cadena de texto.');out+='§'+(strings.push(JSON.stringify(val))-1)+'§'}else out+=c}return {text:out,restore:t=>t.replace(/§(\d+)§/g,(_,i)=>strings[Number(i)]),strings}}
function braceTokens(source){let tokens=[],buf='',q='',depth=0,line=1,start=1;const push=()=>{if(buf.trim())tokens.push({text:buf.trim(),line:start});buf='';start=line};for(let i=0;i<source.length;i++){let c=source[i];if(q){buf+=c;if(c==='\\'&&i+1<source.length)buf+=source[++i];else if(c===q)q='';if(c==='\n')line++;continue}if(c==='"'||c==="'"){q=c;buf+=c;continue}if(c==='/'&&source[i+1]==='/'){while(i<source.length&&source[i]!=='\n')i++;line++;continue}if(c==='/'&&source[i+1]==='*')fail(line,'Usa comentarios //; los comentarios de bloque aún no se admiten.');if(c==='#'&&!buf.trim()){while(i<source.length&&source[i]!=='\n')i++;line++;start=line;continue}if(c==='(')depth++;if(c===')')depth--;if(depth<0)fail(line,'Paréntesis de cierre inesperado.');if(depth===0&&['{','}',';'].includes(c)){push();if(c!==';')tokens.push({text:c,line});start=line}else{if(!buf.trim()&&!/\s/.test(c))start=line;buf+=c}if(c==='\n')line++}push();if(q||depth)fail(line,'Hay una cadena o un paréntesis sin cerrar.');return tokens}
function normalize(source,lang){let vars=new Map(),body=[],mapping=[],indent=1;let currentLine=1;
 const emit=(s,l=currentLine)=>{body.push('    '.repeat(indent)+s);mapping.push(l)};
 const declare=(name,type,l=currentLine)=>{if(!/^[A-Za-z_]\w*$/.test(name))fail(l,'Nombre de variable no compatible.');const previous=[...vars.keys()].find(n=>n.toLowerCase()===name.toLowerCase());if(previous&&previous!==name)fail(l,'PSeInt no distingue mayúsculas: cambia uno de los nombres '+previous+' / '+name+'.');if(!vars.has(name))vars.set(name,{type,line:l});else if(vars.get(name).type!==type){if(['Entero','Real'].includes(type)&&['Entero','Real'].includes(vars.get(name).type))vars.get(name).type='Real';else fail(l,'No se admite cambiar el tipo de una variable.')}};
 function expression(s){const p=protect(s,currentLine);let v=p.text.trim();if(/\[|\]|\{|\}|\?|\b(?:None|null|undefined)\b|=>|:=/.test(v))fail(currentLine,'Esta expresión aún no está incluida en la traducción entre lenguajes.');
  if(lang==='c'&&v.includes('/')){const divisions=[...v.matchAll(/([A-Za-z_]\w*|\d+(?:\.\d+)?)\s*\/\s*([A-Za-z_]\w*|\d+(?:\.\d+)?)/g)];if(divisions.length!==(v.match(/\//g)||[]).length||divisions.some(m=>!m[1].includes('.')&&!m[2].includes('.')&&vars.get(m[1])?.type!=='Real'&&vars.get(m[2])?.type!=='Real'&&!new RegExp('\\(double\\)\\s*'+m[1]+'\\s*/').test(v)))fail(currentLine,'La división entera o compuesta de C todavía no está soportada. Usa operandos double para división real.');}
  if(/\^/.test(v)&&lang!=='python')fail(currentLine,'El operador XOR todavía no está soportado.');
  if(lang==='python'&&(/\b(?:and|or|not)\b/.test(v)))fail(currentLine,'Por ahora, usa una sola comparación por condición al traducir desde Python.');
  if(lang==='python'&&v.includes('%'))fail(currentLine,'El módulo de Python con números negativos requiere una conversión que aún no está disponible.');
  v=v.replace(/\(double\)\s*/g,'').replace(/\bpow\(([^(),]+),\s*([^(),]+)\)/g,'($1 ^ $2)').replace(/\*\*/g,'^').replace(/===|==/g,'=').replace(/!==|!=/g,'<>').replace(/&&/g,' Y ').replace(/\|\|/g,' O ').replace(/!(?!=)/g,' NO ').replace(/\b(?:True|true)\b/g,'Verdadero').replace(/\b(?:False|false)\b/g,'Falso').replace(/%/g,' MOD ');
  if(/\b[A-Za-z_]\w*\s*\(/.test(v))fail(currentLine,'Las llamadas a funciones en expresiones aún no están soportadas.');
  return p.restore(v);
 }
 function infer(s){const p=protect(s,currentLine),v=p.text.trim();if(/^§\d+§$/.test(v))return 'Cadena';if(/[=<>]|\b(?:Verdadero|Falso|Y|O|NO)\b/.test(v))return 'Logico';if(vars.has(v))return vars.get(v).type;if(v.includes('§'))fail(currentLine,'Las operaciones con cadenas todavía no están soportadas.');if(/[\/^]|\d+\.\d+/.test(v)||[...vars].some(([n,t])=>t.type==='Real'&&new RegExp('\\b'+n+'\\b').test(v)))return 'Real';return 'Entero'}
 function assign(name,value,type){let m;const original=value.trim();
  if(lang==='python'&&(m=/^(?:(int|float)\()?input\(([^()]*)\)\)?$/.exec(original))){declare(name,m[1]==='int'?'Entero':m[1]==='float'?'Real':'Cadena');if(m[2].trim())fail(currentLine,'Para conservar la salida, escribe el mensaje con print() y usa input() sin argumentos.');emit('Leer '+name);return}
  if(lang==='javascript'&&(m=/^(?:Number\()?prompt\(([^()]*)\)\)?$/.exec(original))){declare(name,original.startsWith('Number')?'Real':'Cadena');if(m[1].trim())fail(currentLine,'Usa console.log() para el mensaje y prompt() sin argumentos.');emit('Leer '+name);return}
  const v=expression(original);declare(name,type||infer(v));emit(name+' <- '+v);
 }
 function output(values,separator=''){let converted=[];values.forEach((v,i)=>{const e=expression(v);if(infer(e)==='Logico')fail(currentLine,'La salida directa de valores lógicos todavía no está soportada desde este lenguaje.');if(i&&separator)converted.push(JSON.stringify(separator));converted.push(e)});emit('Escribir '+(converted.join(', ')||'""'))}
 function statement(text){let m;
  if(lang==='python'&&(m=/^print\((.*)\)$/.exec(text))){const args=split(m[1]);let sep=' ';const pos=args.findIndex(x=>/^sep\s*=/.test(x));if(pos>=0){const p=protect(args.splice(pos,1)[0].replace(/^sep\s*=\s*/,''),currentLine);if(p.strings.length!==1||!/^§0§$/.test(p.text))fail(currentLine,'sep debe ser un texto literal.');sep=JSON.parse(p.strings[0])}if(args.some(x=>/^end\s*=/.test(x)))fail(currentLine,'print con end personalizado aún no se admite.');output(args.filter(Boolean),sep);return}
  if(lang==='javascript'&&(m=/^console\.log\((.*)\)$/.exec(text))){let args=m[1];const joined=/^\[([\s\S]*)\]\.join\(""\)$/.exec(args);output(split(joined?joined[1]:args).filter(Boolean),joined?'':' ');return}
  if(lang==='c'&&(m=/^puts\((.*)\)$/.exec(text))){output([m[1]]);return}
  if(lang==='c'&&(m=/^printf\((.*)\)$/.exec(text))){const args=split(m[1]),p=protect(args.shift()||'',currentLine);if(p.strings.length!==1||p.text!=='§0§')fail(currentLine,'printf necesita un formato literal.');let fmt=JSON.parse(p.strings[0]);if(!fmt.endsWith('\n'))fail(currentLine,'Usa printf con un salto de línea final para conservar la salida.');fmt=fmt.slice(0,-1);let values=[],buffer='',j=0;for(let i=0;i<fmt.length;i++){if(fmt[i]==='%'){const c=fmt[++i];if(c==='%'){buffer+='%';continue}if(!['d','i','g','s'].includes(c))fail(currentLine,'Formatos admitidos en printf: %d, %i, %g y %s.');if(buffer){values.push(JSON.stringify(buffer));buffer=''}if(!args[j])fail(currentLine,'Faltan argumentos en printf.');values.push(args[j++])}else buffer+=fmt[i]}if(buffer)values.push(JSON.stringify(buffer));if(j!==args.length)fail(currentLine,'Sobran argumentos en printf.');output(values);return}
  if(lang==='c'&&(m=/^scanf\("(%d|%lf|%f|%255s)",\s*&?([A-Za-z_]\w*)\)$/.exec(text))){if(m[1]==='%255s')fail(currentLine,'scanf de cadenas lee palabras: usa PSeInt para entrada de líneas completas.');emit('Leer '+m[2]);return}
  if(lang==='c'&&/^return\s+0$/.test(text))return;
  if(lang==='python'&&text==='pass')return;
  if(lang==='c'&&(m=/^(int|double|float|bool|char)\s+(.+)$/.exec(text))){for(const d of split(m[2])){const a=/^([A-Za-z_]\w*)(?:\[(\d+)\])?(?:\s*=\s*(.+))?$/.exec(d);if(!a)fail(currentLine,'Declaración de C no compatible.');if(m[1]==='char'&&!a[2])fail(currentLine,'Los caracteres individuales de C aún no se admiten.');if(a[2]&&m[1]!=='char')fail(currentLine,'Los arreglos todavía no están soportados.');const type={int:'Entero',double:'Real',float:'Real',bool:'Logico',char:'Cadena'}[m[1]];declare(a[1],type);if(a[3])assign(a[1],a[3],type)}return}
  if(lang==='javascript'&&(m=/^(?:let|const|var)\s+(.+)$/.exec(text))){for(const d of split(m[1])){const a=/^([A-Za-z_]\w*)\s*=\s*(.+)$/.exec(d);if(!a)fail(currentLine,'Inicializa la variable al declararla.');if(vars.has(a[1]))fail(currentLine,'No se admiten variables con el mismo nombre en diferentes bloques.');assign(a[1],a[2])}return}
  if((m=/^([A-Za-z_]\w*)\s*(\+=|-=|\*=|\/=)\s*(.+)$/.exec(text))){assign(m[1],m[1]+' '+m[2][0]+' ('+m[3]+')');return}
  if((m=/^([A-Za-z_]\w*)(\+\+|--)$/.exec(text))){assign(m[1],m[1]+(m[2]==='++'?' + 1':' - 1'));return}
  if((m=/^([A-Za-z_]\w*)\s*=\s*(.+)$/.exec(text))){assign(m[1],m[2],lang==='c'?vars.get(m[1])?.type:undefined);return}
  fail(currentLine,'Instrucción aún no compatible. Usa variables, asignaciones, salida, if/else y bucles básicos.');
 }
 if(lang==='python'){
  const rows=source.split('\n').map((s,i)=>{if(s.includes('\t'))fail(i+1,'Usa espacios para indentar Python.');const p=protect(s,i+1),text=p.restore(p.text.replace(/#.*/,''));return {text:text.trim(),indent:text.length-text.trimStart().length,line:i+1}}).filter(r=>r.text);let pos=0;
  function block(level){while(pos<rows.length){let r=rows[pos];if(r.indent<level)return;if(r.indent>level)fail(r.line,'Indentación inesperada.');currentLine=r.line;if(/^else:/.test(r.text))return;pos++;let m;
   if((m=/^(if|while)\s+(.+):$/.exec(r.text))){const kind=m[1];emit(kind==='if'?'Si '+expression(m[2])+' Entonces':'Mientras '+expression(m[2])+' Hacer');if(!rows[pos]||rows[pos].indent<=level)fail(r.line,'Falta un bloque indentado.');indent++;block(rows[pos].indent);indent--;if(kind==='if'&&rows[pos]?.indent===level&&rows[pos].text==='else:'){pos++;emit('SiNo');if(!rows[pos]||rows[pos].indent<=level)fail(r.line,'Falta el bloque de else.');indent++;block(rows[pos].indent);indent--}emit(kind==='if'?'FinSi':'FinMientras',r.line)}
   else if((m=/^for\s+([A-Za-z_]\w*)\s+in\s+range\((.+)\):$/.exec(r.text))){const args=split(m[2]);if(args.length<1||args.length>3)fail(r.line,'range admite de uno a tres argumentos.');const start=args.length===1?'0':args[0],end=args.length===1?args[0]:args[1],step=args[2]??'1';if(!/^-?\d+$/.test(step)||Number(step)===0)fail(r.line,'El paso debe ser un entero constante distinto de cero.');declare(m[1],'Entero');let suffix=1;while(source.includes('rango_indice_'+suffix)||source.includes('rango_limite_'+suffix)||vars.has('rango_indice_'+suffix))suffix++;const counter='rango_indice_'+suffix,limit='rango_limite_'+suffix;declare(counter,'Entero');declare(limit,'Entero');emit(counter+' <- '+expression(start));emit(limit+' <- '+expression(end));emit('Mientras '+counter+(Number(step)>0?' < ':' > ')+limit+' Hacer');if(!rows[pos]||rows[pos].indent<=level)fail(r.line,'Falta el bloque de for.');indent++;emit(m[1]+' <- '+counter);block(rows[pos].indent);emit(counter+' <- '+counter+' + ('+step+')',r.line);indent--;emit('FinMientras',r.line)}
   else statement(r.text);
  }}block(0);if(pos<rows.length)fail(rows[pos].line,'else sin un if correspondiente.');
 }else{
  const tokens=braceTokens(source);let pos=0;
  if(lang==='c'){if(!/^int\s+main\s*\(\s*(?:void)?\s*\)$/.test(tokens[0]?.text||''))fail(1,'Usa int main(void) { … } como entrada del programa de C.');pos++;if(tokens[pos++]?.text!=='{')fail(1,'Falta la llave de main.');}
  function block(nested=false){while(pos<tokens.length){const t=tokens[pos];currentLine=t.line;if(t.text==='}'){if(!nested)fail(t.line,'Llave de cierre inesperada.');pos++;return}pos++;let m;
   if((m=/^(if|while)\s*\(([\s\S]*)\)$/.exec(t.text))){const kind=m[1];emit(kind==='if'?'Si '+expression(m[2])+' Entonces':'Mientras '+expression(m[2])+' Hacer');if(tokens[pos++]?.text!=='{')fail(t.line,'Usa llaves para delimitar los bloques.');indent++;block(true);indent--;if(kind==='if'&&tokens[pos]?.text==='else'){pos++;emit('SiNo');if(tokens[pos++]?.text!=='{')fail(t.line,'Usa llaves después de else.');indent++;block(true);indent--}emit(kind==='if'?'FinSi':'FinMientras',t.line)}
   else if((m=/^for\s*\(([\s\S]*)\)$/.exec(t.text))){const parts=split(m[1],';');if(parts.length!==3)fail(t.line,'El bucle for necesita inicio, condición y avance.');statement(parts[0]);emit('Mientras '+expression(parts[1])+' Hacer');if(tokens[pos++]?.text!=='{')fail(t.line,'Usa llaves en el bucle for.');indent++;block(true);statement(parts[2]);indent--;emit('FinMientras',t.line)}
   else if(t.text==='do'){emit('Repetir');if(tokens[pos++]?.text!=='{')fail(t.line,'Falta la llave después de do.');indent++;block(true);indent--;const ending=tokens[pos++];const test=/^while\s*\(([\s\S]*)\)$/.exec(ending?.text||'');if(!test)fail(t.line,'Falta while después de do.');emit('Hasta Que NO ('+expression(test[1])+')',t.line)}
   else statement(t.text);
  }if(nested)fail(currentLine,'Falta una llave de cierre.');}block(lang==='c');if(pos<tokens.length)fail(tokens[pos].line,'No se admite código después de main.');
 }
 const declarations=[...vars].map(([n,v])=>'    Definir '+n+' Como '+v.type);return {code:['Algoritmo MiPrograma',...declarations,...body,'FinAlgoritmo'].join('\n'),map:[1,...[...vars.values()].map(v=>v.line),...mapping,currentLine]};
}
