// A small, explicit PSeInt subset: tokenize, parse, type-check, then emit.
export function translate(source, lang='python') {
 const errors=[], vars=new Map(), rows=source.split('\n'); let pos=0, name='MiAlgoritmo', opened=false,closed=false;
 const fail=(line,message)=>{throw {line,message}};
 const reserved=new Set(('and or not True False None if else while for in def return class import from as pass break continue lambda with try except finally raise yield global nonlocal assert del is async await let const var function console prompt Number String Boolean Math int float double char bool void main printf scanf strcpy true false do switch case default sizeof return new null undefined').split(' '));
 const ident=(s,l)=>{if(!/^[A-Za-z_][A-Za-z_0-9]*$/.test(s)||reserved.has(s.toLowerCase())||s.toLowerCase().startsWith('el_')||['print','input','pow','fgets','stdin','sscanf','strcmp','strcspn','tolower'].includes(s.toLowerCase()))fail(l,'Usa un nombre de variable sin palabras reservadas: '+s);return s.toLowerCase()};
 function lex(s,l){let ts=[],i=0;while(i<s.length){let r=s.slice(i),m;if(/^\s/.test(r)){i++;continue}if(r.startsWith('//'))break;if((m=/^("(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')/.exec(r))){let v=m[0].slice(1,-1).replace(/\\(["'\\nrt])/g,(_,c)=>({n:'\n',r:'\r',t:'\t'}[c]??c));ts.push({k:'str',v});i+=m[0].length;continue}if((m=/^(?:\d+(?:\.\d*)?|\.\d+)/.exec(r))){ts.push({k:'num',v:m[0]});i+=m[0].length;continue}if((m=/^[A-Za-z_][A-Za-z_0-9]*/.exec(r))){let v=m[0].toLowerCase();ts.push({k:'id',v});i+=m[0].length;continue}if((m=/^(<=|>=|<>|!=|==|[+*/^%=<>(),-])/.exec(r))){ts.push({k:'op',v:m[0]});i+=m[0].length;continue}fail(l,'Símbolo no compatible en la expresión: '+r[0]);}return ts}
 function expressions(s,l){const ts=lex(s,l);let j=0;const priority={o:1,y:2,'=':3,'==':3,'<>':3,'!=':3,'<':3,'>':3,'<=':3,'>=':3,'+':4,'-':4,'*':5,'/':5,mod:5,'%':5,'^':7};
 function parse(min=0){let t=ts[j++],a;if(!t)fail(l,'Falta una expresión.');if(t.v==='('){a=parse();if(ts[j++]?.v!==')')fail(l,'Falta cerrar un paréntesis.')}else if(['-','+','no'].includes(t.v)){a={kind:'unary',op:t.v,a:parse(6)};a.type=t.v==='no'?'bool':a.a.type;if(t.v==='no'?a.a.type!=='bool':!['int','real'].includes(a.a.type))fail(l,'El operador '+t.v+' no corresponde al tipo de dato.')}else if(t.k==='num')a={kind:'literal',v:t.v,type:t.v.includes('.')?'real':'int'};else if(t.k==='str')a={kind:'literal',v:t.v,type:'str'};else if(['verdadero','falso'].includes(t.v))a={kind:'literal',v:t.v==='verdadero',type:'bool'};else if(t.k==='id'){if(!vars.has(t.v))fail(l,'Declara la variable «'+t.v+'» con Definir antes de usarla.');a={kind:'variable',v:t.v,type:vars.get(t.v)}}else fail(l,'Se encontró «'+t.v+'» donde se esperaba un número, texto, variable o paréntesis de apertura.');
 while(ts[j]&&priority[ts[j].v]>=min){const op=ts[j++].v,p=priority[op],b=parse(op==='^'?p:p+1);let type;
 if(['y','o'].includes(op)){if(a.type!=='bool'||b.type!=='bool')fail(l,'Y y O necesitan condiciones lógicas.');type='bool'}else if(p===3){if(a.type!==b.type&&!(['int','real'].includes(a.type)&&['int','real'].includes(b.type)))fail(l,'No se pueden comparar estos tipos de datos.');type='bool'}else{if(!['int','real'].includes(a.type)||!['int','real'].includes(b.type))fail(l,'Las operaciones aritméticas necesitan números.');if(['mod','%'].includes(op)&&(a.type!=='int'||b.type!=='int'))fail(l,'MOD necesita números enteros.');type=op==='/'||op==='^'||a.type==='real'||b.type==='real'?'real':'int'}a={kind:'binary',op,a,b,type};}return a}
 const result=[parse()];while(ts[j]?.v===','){j++;result.push(parse())}if(j<ts.length)fail(l,'Expresión no compatible cerca de «'+ts[j].v+'».');return result;}
 const expr=(s,l)=>{const a=expressions(s,l);if(a.length!==1)fail(l,'Se esperaba una sola expresión.');return a[0]};
 function clean(s){let quote=null,out='';for(let i=0;i<s.length;i++){let c=s[i];if(quote){out+=c;if(c==='\\'&&i+1<s.length){out+=s[++i];continue}if(c===quote)quote=null}else{if(c==='"'||c==="'")quote=c;if(c==='/'&&s[i+1]==='/')break;out+=c}}return out.trim().replace(/;\s*$/,'')}
 const peek=()=>pos<rows.length?clean(rows[pos]):null;
 const condition=(s,l)=>{const a=expr(s,l);if(a.type!=='bool')fail(l,'La condición debe producir Verdadero o Falso.');return a};
 function block(stops=[]){let out=[];while(pos<rows.length){let text=peek(),line=pos+1;if(stops.some(r=>r.test(text)))break;pos++;if(!text){continue}let m,node={line};
 if((m=/^(Algoritmo|Proceso)\s+([A-Za-z_]\w*)$/i.exec(text))){if(opened||out.length||stops.length)fail(line,'Algoritmo debe aparecer una sola vez, al principio.');opened=true;name=m[2];continue}
 if(/^(FinAlgoritmo|FinProceso)$/i.test(text)){if(!opened)fail(line,'Falta Algoritmo al comienzo.');if(stops.length)fail(line,'Cierra los bloques antes de FinAlgoritmo.');closed=true;if(pos<rows.length&&rows.slice(pos).some(x=>clean(x)))fail(line,'No puede haber instrucciones después de FinAlgoritmo.');break}
 if(!opened)fail(line,'Comienza con Algoritmo y el nombre de tu programa.');
 if((m=/^Definir\s+(.+?)\s+Como\s+(Entero|Real|Cadena|Caracter|Logico|Lógico)$/i.exec(text))){if(stops.length)fail(line,'En esta versión, declara las variables antes de los bloques.');let type={entero:'int',real:'real',cadena:'str',caracter:'str',logico:'bool','lógico':'bool'}[m[2].toLowerCase()];let names=m[1].split(',').map(x=>ident(x.trim(),line));for(const n of names){if(vars.has(n))fail(line,'La variable «'+n+'» ya está declarada.');vars.set(n,type)}node={...node,kind:'declare',names,type}}
 else if((m=/^Escribir\s+(.+)$/i.exec(text)))node={...node,kind:'write',values:expressions(m[1],line)};
 else if((m=/^Leer\s+(.+)$/i.exec(text))){let names=m[1].split(',').map(x=>ident(x.trim(),line));for(const n of names)if(!vars.has(n))fail(line,'Declara «'+n+'» antes de leer su valor.');node={...node,kind:'read',names}}
 else if((m=/^Si\s+(.+?)\s+Entonces$/i.exec(text))){let test=condition(m[1],line),body=block([/^SiNo$/i,/^FinSi$/i]);let other=[];if(/^SiNo$/i.test(peek()??'')){pos++;other=block([/^FinSi$/i])}if(!/^FinSi$/i.test(peek()??''))fail(line,'Falta FinSi para cerrar esta decisión.');pos++;node={...node,kind:'if',test,body,other}}
 else if((m=/^Mientras\s+(.+?)\s+Hacer$/i.exec(text))){let test=condition(m[1],line),body=block([/^FinMientras$/i]);if(!/^FinMientras$/i.test(peek()??''))fail(line,'Falta FinMientras.');pos++;node={...node,kind:'while',test,body}}
 else if(/^Repetir$/i.test(text)){let body=block([/^Hasta\s+Que\s+/i]);m=/^Hasta\s+Que\s+(.+)$/i.exec(peek()??'');if(!m)fail(line,'Falta Hasta Que con su condición.');let test=condition(m[1],pos+1);pos++;node={...node,kind:'repeat',body,test}}
 else if((m=/^Para\s+([A-Za-z_]\w*)\s*(?:<-|:=)\s*(.+?)\s+Hasta\s+(.+?)(?:\s+Con\s+Paso\s+(-?\d+))?\s+Hacer$/i.exec(text))){let v=ident(m[1],line);if(vars.get(v)!=='int')fail(line,'Declara el contador «'+v+'» Como Entero.');let start=expr(m[2],line),end=expr(m[3],line),step=Number(m[4]??1);if(start.type!=='int'||end.type!=='int'||!step)fail(line,'Para necesita límites enteros y un paso entero distinto de cero.');let body=block([/^FinPara$/i]);if(!/^FinPara$/i.test(peek()??''))fail(line,'Falta FinPara.');pos++;node={...node,kind:'for',v,start,end,step,body}}
 else if((m=/^([A-Za-z_]\w*)\s*(?:<-|:=)\s*(.+)$/.exec(text))){let v=ident(m[1],line);if(!vars.has(v))fail(line,'Declara «'+v+'» antes de asignarle un valor.');let value=expr(m[2],line),type=vars.get(v);if(type!==value.type&&!(type==='real'&&value.type==='int'))fail(line,'El valor no coincide con el tipo de «'+v+'».');node={...node,kind:'assign',v,value}}
 else fail(line,'Instrucción no compatible o incompleta. Consulta la guía de sintaxis.');out.push(node);}return out}
 let ast;try{if(!source.trim())return {code:'',errors:[],name:'mi_algoritmo',empty:true};ast=block();if(!closed)fail(rows.length,'Cierra tu programa con FinAlgoritmo.')}catch(e){return {code:'',errors:[{line:e.line??1,message:e.message??'Revisa la sintaxis.'}],name}}
 let lines=[],mapping=[],indent=lang==='c'?1:0;
 function emit(s,line=0){lines.push('    '.repeat(indent)+s);mapping.push(line)}
 const quote=s=>JSON.stringify(s),defaultVal=t=>t==='str'?'""':t==='bool'?(lang==='python'?'False':'false'):'0';
 function ex(a){if(a.kind==='literal')return a.type==='str'?quote(a.v):a.type==='bool'?(a.v?(lang==='python'?'True':'true'):(lang==='python'?'False':'false')):a.v;
 if(a.kind==='variable')return a.v;if(a.kind==='unary')return '('+(a.op==='no'?(lang==='python'?'not ':'!'):a.op)+ex(a.a)+')';let x=ex(a.a),y=ex(a.b),op=a.op;
 if(op==='^')return lang==='c'?`pow(${x}, ${y})`:`(${x} ** ${y})`;
 if(lang==='c'&&a.a.type==='str')return `(strcmp(${x}, ${y}) ${{'=':'==','==':'==','<>':'!=','!=':'!='}[op]??op} 0)`;
 if(op==='/'&&lang==='c')return `((double) ${x} / ${y})`;
 if(op==='mod'||op==='%')return lang==='python'?`(${x} - int(${x} / ${y}) * ${y})`:`(${x} % ${y})`;
 op=({'=':'==','<>':'!=','y':lang==='python'?'and':'&&','o':lang==='python'?'or':'||'})[op]??op;return `(${x} ${op} ${y})`;}
 const end=()=>{indent--;if(lang!=='python')emit('}')};
 function body(nodes){if(!nodes.length&&lang==='python')emit('pass');for(const n of nodes){let l=n.line;switch(n.kind){case 'declare':for(const v of n.names){if(lang==='python')emit(`${v} = ${defaultVal(n.type)}`,l);else if(lang==='javascript')emit(`let ${v} = ${defaultVal(n.type)};`,l);else emit(n.type==='str'?`char ${v}[256] = "";`:`${{int:'int',real:'double',bool:'bool'}[n.type]} ${v} = ${defaultVal(n.type)};`,l)}break;
 case 'write':{const vals=n.values.map(a=>a.type==='bool'?`(${ex(a)} ${lang==='python'?'':'? '}${lang==='python'?'':quote('Verdadero')+' : '+quote('Falso')})`:ex(a));const display=n.values.map(a=>a.type==='bool'?(lang==='python'?`("Verdadero" if ${ex(a)} else "Falso")`:`(${ex(a)} ? "Verdadero" : "Falso")`):ex(a));if(lang==='python')emit(`print(${display.join(', ')}, sep="")`,l);else if(lang==='javascript')emit(`console.log([${display.join(', ')}].join(""));`,l);else{let fmt=n.values.map(a=>a.type==='str'||a.type==='bool'?'%s':a.type==='int'?'%d':'%g').join('')+'\n';emit(`printf(${quote(fmt)}, ${display.join(', ')});`,l)}break}
 case 'read':for(const v of n.names){let t=vars.get(v);if(lang==='python')emit(`${v} = ${{int:'int(input())',real:'float(input())',str:'input()',bool:'input().strip().lower() in ("verdadero", "true", "1")'}[t]}`,l);else if(lang==='javascript')emit(`${v} = ${{int:'Math.trunc(Number(prompt("'+v+'")))',real:'Number(prompt("'+v+'"))',str:'(prompt("'+v+'") ?? "")',bool:'["verdadero", "true", "1"].includes((prompt("'+v+'") ?? "").trim().toLowerCase())'}[t]};`,l);else{emit('{',l);indent++;emit('char el_input[256];');emit('if (!fgets(el_input, sizeof el_input, stdin)) return 1;');if(t==='str'){emit('el_input[strcspn(el_input, "\\r\\n")] = 0;');emit(`strcpy(${v}, el_input);`)}else if(t==='bool'){emit('for (int el_i = 0; el_input[el_i]; el_i++) el_input[el_i] = (char)tolower((unsigned char)el_input[el_i]);');emit('el_input[strcspn(el_input, "\\r\\n")] = 0;');emit(`${v} = strcmp(el_input, "verdadero") == 0 || strcmp(el_input, "true") == 0 || strcmp(el_input, "1") == 0;`)}else emit(`if (sscanf(el_input, "${t==='int'?'%d':'%lf'}", &${v}) != 1) return 1;`);indent--;emit('}')}}break;
 case 'assign':emit(lang==='c'&&n.value.type==='str'?`strcpy(${n.v}, ${ex(n.value)});`:`${n.v} = ${ex(n.value)}${lang==='python'?'':';'}`,l);break;
 case 'if':emit(lang==='python'?`if ${ex(n.test)}:`:`if (${ex(n.test)}) {`,l);indent++;body(n.body);end();if(n.other.length){emit(lang==='python'?'else:':'else {',l);indent++;body(n.other);end()}break;
 case 'while':emit(lang==='python'?`while ${ex(n.test)}:`:`while (${ex(n.test)}) {`,l);indent++;body(n.body);end();break;
 case 'repeat':emit(lang==='python'?'while True:':lang==='c'?'do {':'while (true) {',l);indent++;body(n.body);if(lang==='c'){indent--;emit(`} while (!${ex(n.test)});`,l)}else{emit(lang==='python'?`if ${ex(n.test)}:`:`if (${ex(n.test)}) {`,l);indent++;emit(lang==='python'?'break':'break;');end();end()}break;
 case 'for':emit(`${n.v} = ${ex(n.start)}${lang==='python'?'':';'}`,l);emit(lang==='python'?`while ${n.v} ${n.step>0?'<=':'>='} ${ex(n.end)}:`:`while (${n.v} ${n.step>0?'<=':'>='} ${ex(n.end)}) {`,l);indent++;body(n.body);emit(`${n.v} += ${n.step}${lang==='python'?'':';'}`,l);end();break;
 }}}
 if(lang==='c'){indent=0;emit('#include <stdio.h>');emit('#include <stdbool.h>');emit('#include <string.h>');emit('#include <ctype.h>');emit('#include <math.h>');emit('');emit('int main(void) {');indent=1}else emit((lang==='python'?'# ':'// ')+name);
 body(ast);if(lang==='c'){emit('return 0;');indent=0;emit('}')}
 return {code:lines.join('\n'),errors,mapping,name,ast};
}
